services:
  - type: web
    name: cms
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
